# conda env create -f environment_dev.yml
# conda activate ./envs
# conda env update --file environment_dev.yml --prune

name: cofi_dev
channels: 
  - conda-forge
dependencies:
  - numpy
  - scipy
  - pyyaml
  - setuptools
  - black
  - sphinx
  - pip
  - pip:
    - insipid-sphinx-theme
