name: cofi_test
dependencies:
  - numpy>=1.22.1
  - scipy>=1.7.3
  - matplotlib>=3.5.0
  - scikit-build>=0.11.1
  - pytest>=6.2.5
  - conda-forge::petsc4py>=3.16.1
  - pip>=21.2.4
  - pip:
    - coverage[toml]>=6.2
