# python -m build
# python setup.py develop [--uninstall] | pip install -e . (preferred)
[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

# black --check .
# black .
[tool.black]
line-length = 88
target_version = ['py37', 'py38']
experimental_string_processing = true
exclude = '''
/(
   \.git
  | \.mypy_cache
  | \.vscode
  | build
  | dist
  | docs
  | examples
  | lib
)/
'''