name: Workflow for Codecov CoFI
on: [push, pull_request]
jobs:
  code_coverage:
    name: Run coverage on ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Set up environment
        run: |
          $CONDA/bin/conda install -c conda-forge gfortran
          $CONDA/bin/conda install numpy scipy petsc petsc4py matplotlib cython pybind11 scikit-build pytest pip
          $CONDA/bin/pip install coverage
          $CONDA/bin/pip install .
      - name: Run tests and collect coverage
        run: |
          $CONDA/bin/coverage run -m pytest
          $CONDA/bin/coverage xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2